//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string WPF_Add {
            get {
                return ResourceManager.GetString("WPF_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string WPF_Back {
            get {
                return ResourceManager.GetString("WPF_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel métier.
        /// </summary>
        public static string WPF_BusinessApp {
            get {
                return ResourceManager.GetString("WPF_BusinessApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel métier détecté, travail mis en pause.
        /// </summary>
        public static string WPF_BusinessAppDetect {
            get {
                return ResourceManager.GetString("WPF_BusinessAppDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir source.
        /// </summary>
        public static string WPF_ChooseFrom {
            get {
                return ResourceManager.GetString("WPF_ChooseFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir destination.
        /// </summary>
        public static string WPF_ChooseTo {
            get {
                return ResourceManager.GetString("WPF_ChooseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string WPF_Create {
            get {
                return ResourceManager.GetString("WPF_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un travail de sauvegarde.
        /// </summary>
        public static string WPF_CreateSave {
            get {
                return ResourceManager.GetString("WPF_CreateSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string WPF_Delete {
            get {
                return ResourceManager.GetString("WPF_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle.
        /// </summary>
        public static string WPF_Differential {
            get {
                return ResourceManager.GetString("WPF_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions à crypter.
        /// </summary>
        public static string WPF_EncryptExtension {
            get {
                return ResourceManager.GetString("WPF_EncryptExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rentrer un nom de travail de sauvegarde.
        /// </summary>
        public static string WPF_EnterNameSave {
            get {
                return ResourceManager.GetString("WPF_EnterNameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier votre dossier de source et de destination.
        /// </summary>
        public static string WPF_ErrorCreate {
            get {
                return ResourceManager.GetString("WPF_ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptage de fichiers.
        /// </summary>
        public static string WPF_FileEncrypt {
            get {
                return ResourceManager.GetString("WPF_FileEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string WPF_From {
            get {
                return ResourceManager.GetString("WPF_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complète.
        /// </summary>
        public static string WPF_Full {
            get {
                return ResourceManager.GetString("WPF_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion.
        /// </summary>
        public static string WPF_Manage {
            get {
                return ResourceManager.GetString("WPF_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille maximum transfert simultané.
        /// </summary>
        public static string WPF_MaxSize {
            get {
                return ResourceManager.GetString("WPF_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string WPF_Name {
            get {
                return ResourceManager.GetString("WPF_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string WPF_Pause {
            get {
                return ResourceManager.GetString("WPF_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression.
        /// </summary>
        public static string WPF_Progression {
            get {
                return ResourceManager.GetString("WPF_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string WPF_Save {
            get {
                return ResourceManager.GetString("WPF_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des travaux de sauvegarde.
        /// </summary>
        public static string WPF_SaveList {
            get {
                return ResourceManager.GetString("WPF_SaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde.
        /// </summary>
        public static string WPF_SaveType {
            get {
                return ResourceManager.GetString("WPF_SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string WPF_Settings {
            get {
                return ResourceManager.GetString("WPF_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer.
        /// </summary>
        public static string WPF_Start {
            get {
                return ResourceManager.GetString("WPF_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string WPF_Stop {
            get {
                return ResourceManager.GetString("WPF_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string WPF_To {
            get {
                return ResourceManager.GetString("WPF_To", resourceCulture);
            }
        }
    }
}
